# Generated by Django 3.1.5 on 2021-02-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_auto_20210128_1653"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True, null=True)),
                ("status", models.CharField(max_length=10)),
                ("red", models.CharField(max_length=40)),
                ("blue", models.CharField(max_length=40)),
                ("betRed", models.IntegerField()),
                ("betBlue", models.IntegerField()),
                ("covariance", models.FloatField()),
                ("avgDiff", models.FloatField()),
                ("n", models.IntegerField()),
                ("balance", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="champion",
            name="elo",
        ),
    ]
