# Generated by Django 3.1.5 on 2021-02-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_auto_20210201_2121"),
    ]

    operations = [
        migrations.AddField(
            model_name="champion",
            name="avgBetShare",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="matchup",
            name="betShare1",
            field=models.FloatField(default=0),
        ),
    ]
