# Generated by Django 3.1.5 on 2021-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('elo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redName', models.CharField(max_length=40)),
                ('blueName', models.CharField(max_length=40)),
                ('NScoreDifference', models.FloatField()),
                ('redTotalBets', models.IntegerField()),
                ('blueTotalBets', models.IntegerField()),
                ('bet', models.IntegerField()),
                ('redWin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=40)),
                ('name2', models.CharField(max_length=40)),
                ('wins1', models.CharField(max_length=40)),
                ('wins2', models.CharField(max_length=40)),
            ],
        ),
    ]
