# Generated by Django 3.1.5 on 2021-02-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210202_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='blue',
            new_name='looser',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='blueTotalBets',
            new_name='looserTotalBets',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='red',
            new_name='winner',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='redTotalBets',
            new_name='winnerTotalBets',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='match',
            name='redWin',
        ),
    ]
